Repository codesquad-member-2020/todo-12, pull requests merged in 2020-04, with the labels that each got.

#2 [iOS] 최초 프로젝트 생성 및 풀리퀘스트 테스트
  iOS/.gitignore
  iOS/ToDo/ToDo.xcodeproj/project.pbxproj
  iOS/ToDo/ToDo.xcodeproj/project.xcworkspace/contents.xcworkspacedata
  iOS/ToDo/ToDo.xcodeproj/project.xcworkspace/xcshareddata/IDEWorkspaceChecks.plist
  iOS/ToDo/ToDo.xcodeproj/xcuserdata/hanseop.xcuserdatad/xcschemes/xcschememanagement.plist
  iOS/ToDo/ToDo/AppDelegate.swift
  iOS/ToDo/ToDo/Assets.xcassets/AppIcon.appiconset/Contents.json
  iOS/ToDo/ToDo/Assets.xcassets/Contents.json
  iOS/ToDo/ToDo/Base.lproj/LaunchScreen.storyboard
  iOS/ToDo/ToDo/Base.lproj/Main.storyboard
  iOS/ToDo/ToDo/Info.plist
  iOS/ToDo/ToDo/SceneDelegate.swift
  iOS/ToDo/ToDo/ViewController.swift
  iOS/ToDo/ToDoTests/Info.plist
  iOS/ToDo/ToDoTests/ToDoTests.swift
Labels: feature

#10 #1 공통 UI 구성
  iOS/ToDo/ToDo.xcodeproj/project.pbxproj
  iOS/ToDo/ToDo/Base.lproj/Main.storyboard
  iOS/ToDo/ToDo/Controller/AppDelegate.swift
  iOS/ToDo/ToDo/Controller/SceneDelegate.swift
  iOS/ToDo/ToDo/Info.plist
  iOS/ToDo/ToDo/TableViewController.swift
  iOS/ToDo/ToDo/View/Base.lproj/LaunchScreen.storyboard
  iOS/ToDo/ToDo/View/Base.lproj/Main.storyboard
  iOS/ToDo/ToDo/View/HistoryTableViewController.swift
  iOS/ToDo/ToDo/View/TaskViewController.swift
  iOS/ToDo/ToDo/View/ViewController.swift
  iOS/ToDo/ToDo/ViewController.swift
Labels: feature

#14 [#8] UI 구성 - task 관련 UI 구성
  iOS/ToDo/ToDo.xcodeproj/project.pbxproj
  iOS/ToDo/ToDo/Controller/ContentsTextViewDelegate.swift
  iOS/ToDo/ToDo/Controller/SceneDelegate.swift
  iOS/ToDo/ToDo/Controller/contextMenuDelegate.swift
  iOS/ToDo/ToDo/Controller/todoTableViewDelegate.swift
  iOS/ToDo/ToDo/Info.plist
  iOS/ToDo/ToDo/View/Base.lproj/Main.storyboard
  iOS/ToDo/ToDo/View/EditTaskViewController.swift
  iOS/ToDo/ToDo/View/TaskViewController.swift
  iOS/ToDo/ToDo/View/taskCell.swift
  iOS/ToDo/ToDo/View/todoDataSource.swift
Labels: feature

#20 [#16] Network 통신
  iOS/ToDo/ToDo.xcodeproj/project.pbxproj
  iOS/ToDo/ToDo/Info.plist
  iOS/ToDo/ToDo/Model/Card.swift
  iOS/ToDo/ToDo/Model/Category.swift
  iOS/ToDo/ToDo/Model/Model.swift
  iOS/ToDo/ToDo/Model/NetworkConnection.swift
  iOS/ToDo/ToDo/View/StoryBoard/Base.lproj/LaunchScreen.storyboard
  iOS/ToDo/ToDo/View/StoryBoard/Base.lproj/Main.storyboard
  iOS/ToDo/ToDo/View/TaskView/Cell/TaskCell.swift
  iOS/ToDo/ToDo/View/TaskView/DataSource/TodoDataSource.swift
  iOS/ToDo/ToDo/View/TaskView/EditTaskViewController.swift
  iOS/ToDo/ToDo/View/TaskView/HistoryTableViewController.swift
  iOS/ToDo/ToDo/View/TaskView/TaskViewController.swift
  iOS/ToDo/ToDo/View/ViewController.swift
Labels: feature

#28 [BE] 카드, 카테고리 CRUD API 구현
  BE/todo-12/build.gradle
  BE/todo-12/src/main/java/dev/codesquad/java/todo12/ApiCardController.java
  BE/todo-12/src/main/java/dev/codesquad/java/todo12/ApiCategoryController.java
  BE/todo-12/src/main/java/dev/codesquad/java/todo12/Card.java
  BE/todo-12/src/main/java/dev/codesquad/java/todo12/CardRepository.java
  BE/todo-12/src/main/java/dev/codesquad/java/todo12/Category.java
  BE/todo-12/src/main/java/dev/codesquad/java/todo12/CategoryRepository.java
  BE/todo-12/src/main/java/dev/codesquad/java/todo12/DataNotFoundException.java
  BE/todo-12/src/main/java/dev/codesquad/java/todo12/Kanban.java
  BE/todo-12/src/main/java/dev/codesquad/java/todo12/KanbanRepository.java
  BE/todo-12/src/main/java/dev/codesquad/java/todo12/MockUpController.java
  BE/todo-12/src/main/java/dev/codesquad/java/todo12/Todo12Application.java
  BE/todo-12/src/main/resources/application.properties
  BE/todo-12/src/main/resources/data.sql
  BE/todo-12/src/main/resources/schema.sql
Labels: feature

#37 [#36] contextMenu 기능 완성 - move to done, delete
  iOS/ToDo/ToDo/Controller/CardTableViewDelegate.swift
  iOS/ToDo/ToDo/View/BoardViewController.swift
Labels: feature

#41 [#38] refactoring
  iOS/ToDo/ToDo/Controller/CardTableViewDelegate.swift
  iOS/ToDo/ToDo/Controller/TableViewDropDelegate.swift
  iOS/ToDo/ToDo/View/BoardViewController.swift
  iOS/ToDo/ToDo/View/CardView/CardViewController.swift
  iOS/ToDo/ToDo/View/CardView/DataSource/CardDataSource.swift
Labels: refactor

#43 [BE] soft / hard delete 기능 구현
  BE/todo-12/.idea/compiler.xml
  BE/todo-12/.idea/misc.xml
  BE/todo-12/src/main/java/dev/codesquad/java/todo12/ApiCardController.java
  BE/todo-12/src/main/java/dev/codesquad/java/todo12/ApiCategoryController.java
  BE/todo-12/src/main/java/dev/codesquad/java/todo12/ApiHomeController.java
  BE/todo-12/src/main/java/dev/codesquad/java/todo12/Card.java
  BE/todo-12/src/main/java/dev/codesquad/java/todo12/CardRepository.java
  BE/todo-12/src/main/java/dev/codesquad/java/todo12/Category.java
  BE/todo-12/src/main/java/dev/codesquad/java/todo12/CategoryRepository.java
  BE/todo-12/src/main/java/dev/codesquad/java/todo12/Kanban.java
  BE/todo-12/src/main/java/dev/codesquad/java/todo12/MockUpController.java
  BE/todo-12/src/main/java/dev/codesquad/java/todo12/WebConfig.java
  BE/todo-12/src/main/resources/data.sql
  BE/todo-12/src/main/resources/schema.sql
  README.md
Labels: feature

#48 [BE] DB 업데이트 및 버그 수정
  BE/todo-12/src/main/java/dev/codesquad/java/todo12/ApiCardController.java
  BE/todo-12/src/main/java/dev/codesquad/java/todo12/ApiCategoryController.java
  BE/todo-12/src/main/java/dev/codesquad/java/todo12/ApiHomeController.java
  BE/todo-12/src/main/java/dev/codesquad/java/todo12/Card.java
  BE/todo-12/src/main/java/dev/codesquad/java/todo12/Category.java
  BE/todo-12/src/main/java/dev/codesquad/java/todo12/WebConfig.java
  BE/todo-12/src/main/resources/application.properties
  BE/todo-12/src/main/resources/schema.sql
  README.md
Labels: bug, refactor

#53 [#42] refactoring
  iOS/ToDo/ToDo.xcodeproj/project.pbxproj
  iOS/ToDo/ToDo/Controller/CardTableViewDelegate.swift
  iOS/ToDo/ToDo/Controller/TableViewDragDelegate.swift
  iOS/ToDo/ToDo/Controller/TableViewDropDelegate.swift
  iOS/ToDo/ToDo/Model/Card.swift
  iOS/ToDo/ToDo/Model/CardManager.swift
  iOS/ToDo/ToDo/Model/Category.swift
  iOS/ToDo/ToDo/Model/CategoryManager.swift
  iOS/ToDo/ToDo/Model/Model.swift
  iOS/ToDo/ToDo/Model/NetworkConnection.swift
  iOS/ToDo/ToDo/View/BoardViewController.swift
  iOS/ToDo/ToDo/View/CardView/CardViewController.swift
  iOS/ToDo/ToDo/View/CardView/Cell/CardCell.swift
  iOS/ToDo/ToDo/View/CardView/DataSource/CardDataSource.swift
Labels: refactor

#56 [BE] history API 기능 추가
  BE/todo-12/src/main/java/dev/codesquad/java/todo12/ApiCardController.java
  BE/todo-12/src/main/java/dev/codesquad/java/todo12/ApiCategoryController.java
  BE/todo-12/src/main/java/dev/codesquad/java/todo12/ApiHomeController.java
  BE/todo-12/src/main/java/dev/codesquad/java/todo12/Card.java
  BE/todo-12/src/main/java/dev/codesquad/java/todo12/CardService.java
  BE/todo-12/src/main/java/dev/codesquad/java/todo12/Category.java
  BE/todo-12/src/main/java/dev/codesquad/java/todo12/CategoryRepository.java
  BE/todo-12/src/main/java/dev/codesquad/java/todo12/CategoryService.java
  BE/todo-12/src/main/java/dev/codesquad/java/todo12/History.java
  BE/todo-12/src/main/java/dev/codesquad/java/todo12/HistoryRepository.java
  BE/todo-12/src/main/java/dev/codesquad/java/todo12/Kanban.java
  BE/todo-12/src/main/java/dev/codesquad/java/todo12/StaticApiUtils.java
  BE/todo-12/src/main/resources/data.sql
  BE/todo-12/src/main/resources/schema.sql
  README.md
Labels: feature

#60 [#39] connect network
  iOS/ToDo/ToDo.xcodeproj/project.pbxproj
  iOS/ToDo/ToDo/Model/Card.swift
  iOS/ToDo/ToDo/Model/CategoryManager.swift
  iOS/ToDo/ToDo/Model/DateExtension.swift
  iOS/ToDo/ToDo/Model/NetworkConnection.swift
  iOS/ToDo/ToDo/View/BoardViewController.swift
  iOS/ToDo/ToDo/View/CardView/CardViewController.swift
  iOS/ToDo/ToDo/View/CardView/EditCardViewController.swift
  iOS/ToDo/ToDo/View/StoryBoard/Base.lproj/Main.storyboard
Labels: feature

#65 [#61] history table view
  iOS/ToDo/ToDo.xcodeproj/project.pbxproj
  iOS/ToDo/ToDo/Assets.xcassets/codesquad2.imageset/Contents.json
  iOS/ToDo/ToDo/Assets.xcassets/codesquad2.imageset/codesquad2.png
  iOS/ToDo/ToDo/Model/Card/Card.swift
  iOS/ToDo/ToDo/Model/Card/CardManager.swift
  iOS/ToDo/ToDo/Model/Category/Category.swift
  iOS/ToDo/ToDo/Model/Category/CategoryManager.swift
  iOS/ToDo/ToDo/Model/DateExtension.swift
  iOS/ToDo/ToDo/Model/Extension/DateExtension.swift
  iOS/ToDo/ToDo/Model/Extension/NSMutableAttributedStringExtension.swift
  iOS/ToDo/ToDo/Model/History/History.swift
  iOS/ToDo/ToDo/Model/History/HistoryManager.swift
  iOS/ToDo/ToDo/Model/Network/NetworkConnection.swift
  iOS/ToDo/ToDo/View/BoardView/BoardViewController.swift
  iOS/ToDo/ToDo/View/CardView/HistoryTableViewController.swift
  iOS/ToDo/ToDo/View/EditView/EditCardViewController.swift
  iOS/ToDo/ToDo/View/HistoryView/Cell/HistoryCell.swift
  iOS/ToDo/ToDo/View/HistoryView/HistoryTableViewController.swift
  iOS/ToDo/ToDo/View/StoryBoard/Base.lproj/Main.storyboard
Labels: feature

#68 [BE] JWT 기능 추가
  BE/todo-12/build.gradle
  BE/todo-12/src/main/java/dev/codesquad/java/todo12/ApiAccessController.java
  BE/todo-12/src/main/java/dev/codesquad/java/todo12/ApiCardController.java
  BE/todo-12/src/main/java/dev/codesquad/java/todo12/ApiCategoryController.java
  BE/todo-12/src/main/java/dev/codesquad/java/todo12/Card.java
  BE/todo-12/src/main/java/dev/codesquad/java/todo12/CardService.java
  BE/todo-12/src/main/java/dev/codesquad/java/todo12/Category.java
  BE/todo-12/src/main/java/dev/codesquad/java/todo12/ExceptionAdvice.java
  BE/todo-12/src/main/java/dev/codesquad/java/todo12/History.java
  BE/todo-12/src/main/java/dev/codesquad/java/todo12/InvalidTokenException.java
  BE/todo-12/src/main/java/dev/codesquad/java/todo12/StaticApiUtils.java
  BE/todo-12/src/main/java/dev/codesquad/java/todo12/TokenInterceptor.java
  BE/todo-12/src/main/java/dev/codesquad/java/todo12/TokenService.java
  BE/todo-12/src/main/java/dev/codesquad/java/todo12/UnauthorizedException.java
  BE/todo-12/src/main/java/dev/codesquad/java/todo12/User.java
  BE/todo-12/src/main/java/dev/codesquad/java/todo12/UserRepository.java
  BE/todo-12/src/main/java/dev/codesquad/java/todo12/WebMvcConfig.java
  BE/todo-12/src/main/resources/data.sql
Labels: feature
